// AUTO-GENERATED by scripts/process-images.ts — do not edit by hand
export type ShopImage = {
  slug: string;
  alt: string;
  category: "wide" | "portrait";
  widths: number[];
  formats: ("webp" | "avif")[];
};

export type Video = {
  src: string;
  poster?: string;
};

export const shopImages: ShopImage[] = [
  {
    "slug": "img20251029123655",
    "alt": "Saw Service 3G — on-site shop work",
    "category": "portrait",
    "widths": [
      640,
      1024,
      1600
    ],
    "formats": [
      "webp",
      "avif"
    ]
  },
  {
    "slug": "img20260216135655",
    "alt": "Saw Service 3G — on-site shop work",
    "category": "portrait",
    "widths": [
      640,
      1024,
      1600
    ],
    "formats": [
      "webp",
      "avif"
    ]
  },
  {
    "slug": "img20260317153541",
    "alt": "Saw Service 3G — on-site shop work",
    "category": "portrait",
    "widths": [
      640,
      1024,
      1600
    ],
    "formats": [
      "webp",
      "avif"
    ]
  },
  {
    "slug": "img-20200319-155254",
    "alt": "Saw Service 3G — on-site shop work",
    "category": "wide",
    "widths": [
      640,
      1024,
      1600
    ],
    "formats": [
      "webp",
      "avif"
    ]
  },
  {
    "slug": "screenshot-2026-05-03-22-12-14-65-965bbf4d18d205f782c6b8409c5773a4",
    "alt": "Saw Service 3G — on-site shop work",
    "category": "wide",
    "widths": [
      640,
      1024,
      1600
    ],
    "formats": [
      "webp",
      "avif"
    ]
  },
  {
    "slug": "screenshot-2026-05-03-22-13-22-31-965bbf4d18d205f782c6b8409c5773a4",
    "alt": "Saw Service 3G — on-site shop work",
    "category": "wide",
    "widths": [
      640,
      1024,
      1600
    ],
    "formats": [
      "webp",
      "avif"
    ]
  },
  {
    "slug": "screenshot-2026-05-03-22-14-35-48-965bbf4d18d205f782c6b8409c5773a4",
    "alt": "Saw Service 3G — on-site shop work",
    "category": "portrait",
    "widths": [
      640,
      1024,
      1600
    ],
    "formats": [
      "webp",
      "avif"
    ]
  },
  {
    "slug": "screenshot-2026-05-03-22-14-46-79-965bbf4d18d205f782c6b8409c5773a4",
    "alt": "Saw Service 3G — on-site shop work",
    "category": "portrait",
    "widths": [
      640,
      1024,
      1600
    ],
    "formats": [
      "webp",
      "avif"
    ]
  },
  {
    "slug": "screenshot-2026-05-03-22-15-45-37-965bbf4d18d205f782c6b8409c5773a4",
    "alt": "Saw Service 3G — on-site shop work",
    "category": "portrait",
    "widths": [
      640,
      1024,
      1600
    ],
    "formats": [
      "webp",
      "avif"
    ]
  },
  {
    "slug": "screenshot-2026-05-03-22-17-17-96-92460851df6f172a4592fca41cc2d2e6",
    "alt": "Saw Service 3G — on-site shop work",
    "category": "wide",
    "widths": [
      640,
      1024,
      1600
    ],
    "formats": [
      "webp",
      "avif"
    ]
  },
  {
    "slug": "screenshot-2026-05-04-20-50-03-32-92460851df6f172a4592fca41cc2d2e6",
    "alt": "Saw Service 3G — on-site shop work",
    "category": "portrait",
    "widths": [
      640,
      1024,
      1600
    ],
    "formats": [
      "webp",
      "avif"
    ]
  },
  {
    "slug": "gulf-stream-container-inspection",
    "alt": "Saw Service 3G — on-site shop work",
    "category": "portrait",
    "widths": [
      640,
      1024,
      1600
    ],
    "formats": [
      "webp",
      "avif"
    ]
  }
];

export const videos: Video[] = [
  {
    "src": "/video/vid20260129135749.mp4"
  }
];
