/* eslint-disable @typescript-eslint/no-require-imports */
import { copyFile, mkdir, readdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "pictures");
const VID_SRC = path.join(SRC, "videos");
const OUT = path.join(ROOT, "public", "images", "shop");
const VID_OUT = path.join(ROOT, "public", "video");
const WIDTHS = [640, 1024, 1600];

type ShopImage = {
  slug: string;
  alt: string;
  category: "wide" | "portrait";
  widths: number[];
  formats: ("webp" | "avif")[];
  poster?: string;
};

type Video = {
  src: string;
  poster?: string;
};

function slugify(name: string) {
  return name
    .replace(/\.(jpg|jpeg|png|mp4|mov)$/i, "")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
}

async function processOne(file: string) {
  const slug = slugify(file);
  const inputPath = path.join(SRC, file);
  const isScreenshot = /^Screenshot/i.test(file);

  // 1) Auto-rotate.
  // 2) For screenshots: crop the phone status bar (top ~6.5%) and nav bar
  //    (bottom ~5%) — these are NOT plain black so .trim() can't remove them.
  // 3) Then .trim() with a generous threshold to drop the inner black
  //    letterbox bars that bracket the actual photo.
  const pre = await sharp(inputPath)
    .rotate()
    .toBuffer({ resolveWithObject: true });

  let workingBuf = pre.data;
  let workingW = pre.info.width;
  let workingH = pre.info.height;

  if (isScreenshot) {
    // Re-derive dimensions from the buffer in case rotate-on-orient changed them.
    const meta = await sharp(workingBuf).metadata();
    const realW = meta.width ?? workingW;
    const realH = meta.height ?? workingH;
    const topCrop = Math.round(realH * 0.065);
    const bottomCrop = Math.round(realH * 0.055);
    const newH = realH - topCrop - bottomCrop;
    if (newH > 100 && realW > 100) {
      const cropped = await sharp(workingBuf)
        .extract({ left: 0, top: topCrop, width: realW, height: newH })
        .toBuffer({ resolveWithObject: true });
      // Trim in a fresh pipeline to avoid stale extract metadata issues.
      const trimmed = await sharp(cropped.data)
        .trim({ threshold: 25 })
        .toBuffer({ resolveWithObject: true });
      workingBuf = trimmed.data;
      workingW = trimmed.info.width;
      workingH = trimmed.info.height;
    }
  }

  const widthsOut: number[] = [];
  for (const w of WIDTHS) {
    const baseName = `${slug}-${w}`;
    const webpOut = path.join(OUT, `${baseName}.webp`);
    const avifOut = path.join(OUT, `${baseName}.avif`);
    try {
      const pipeline = sharp(workingBuf).resize({
        width: w,
        withoutEnlargement: true,
      });
      await pipeline.clone().webp({ quality: 78, effort: 4 }).toFile(webpOut);
      await pipeline.clone().avif({ quality: 50, effort: 4 }).toFile(avifOut);
      widthsOut.push(w);
      console.log(`[images] ${baseName} -> webp + avif`);
    } catch (err) {
      console.error(`[images] failed for ${file} @ ${w}px`, err);
    }
  }

  if (widthsOut.length === 0) return null;

  const category: ShopImage["category"] = workingH > workingW ? "portrait" : "wide";

  return {
    slug,
    alt: "Saw Service 3G — on-site shop work",
    category,
    widths: widthsOut,
    formats: ["webp", "avif"] as const,
  };
}

async function processVideos() {
  if (!existsSync(VID_SRC)) return [] as Video[];
  await mkdir(VID_OUT, { recursive: true });

  const files = await readdir(VID_SRC);
  const videos: Video[] = [];
  for (const file of files) {
    if (!/\.(mp4|mov|webm)$/i.test(file)) continue;
    const slug = slugify(file);
    const ext = path.extname(file).toLowerCase().replace(".", "");
    const dest = `${slug}.${ext}`;
    await copyFile(path.join(VID_SRC, file), path.join(VID_OUT, dest));
    videos.push({ src: `/video/${dest}` });
    console.log(`[video]  copied ${dest}`);
  }
  return videos;
}

async function main() {
  if (!existsSync(SRC)) {
    console.warn(`[images] no pictures/ — skipping`);
    return;
  }

  await mkdir(OUT, { recursive: true });

  const files = (await readdir(SRC))
    .filter((f) => /\.(jpg|jpeg|png)$/i.test(f))
    .sort();

  const manifest: ShopImage[] = [];
  for (const file of files) {
    const entry = await processOne(file);
    if (entry) {
      manifest.push({
        ...entry,
        formats: [...entry.formats],
      });
    }
  }

  const videos = await processVideos();

  await writeFile(
    path.join(ROOT, "public", "images", "manifest.json"),
    JSON.stringify({ images: manifest, videos }, null, 2),
  );

  const ts = `// AUTO-GENERATED by scripts/process-images.ts — do not edit by hand
export type ShopImage = {
  slug: string;
  alt: string;
  category: "wide" | "portrait";
  widths: number[];
  formats: ("webp" | "avif")[];
};

export type Video = {
  src: string;
  poster?: string;
};

export const shopImages: ShopImage[] = ${JSON.stringify(manifest, null, 2)};

export const videos: Video[] = ${JSON.stringify(videos, null, 2)};
`;
  await writeFile(path.join(ROOT, "data", "images.ts"), ts);

  console.log(
    `[images] wrote manifest + data/images.ts (${manifest.length} images, ${videos.length} videos)`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
